#Versi Python
runtime: python37

#Perangkat yang kita akan pakai, yaitu : F2
instance_class: F2

#Nama servis, ini yang pertama jadi harus default
service: default

handlers:
#directory untuk static
- url: /static
  static_dir: static

#Penanganan URL selain untuk berkas-berkas statis
- url: /.*
  script: auto